jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4

      - name: Install wasm-bindgen and wasm-opt
        run: |
          cargo install wasm-bindgen-cli
          sudo apt update && sudo apt install -y binaryen

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
